name: Build/Preview

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main
      - versionAstro
  pull_request:
    branches:
      - main
      - versionAstro

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Instalar dependencias
        run: npm ci
      - name: Compilar proyecto
        run: npm run build
      - name: Mostrar mensaje personalizado si falla la compilación
        if: failure()
        run: |
          echo "❌ La compilación de producción ha fallado."
          echo "Por favor revisa los errores y corrígelos antes de continuar."
          echo "Documentación: https://vitejs.dev/guide/build.html"
